language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: morning-atoll-35110
  api_key:
    secure: u0QwxmGdcZO6IL2KO9nC7HTgDuBk98aZOB8DTvCCrUA0ZYp7zrrdVloGYpp1eFRdbpYqkX0CPQTDIwsCoqhSRdoChVyvrv7xW3d/v90uH37m3mGR1mCcmT3n6L7RiFIuvYDAEOR2BoL1m2EMIEyZd/APQnc6f6jU0WNXiV0xWhMuLLGjI9/Dw++Fd0ba0H2VmqoEiSIjlWnx/CeHFsfJrOIuO1Yjt+g5aOWCGVyHjyOjRmohdP8Z5NcfHY1ZJaCs5kLu99fmaZXdoR1hw9O2H+rj2q3a0aIPtZwdTek4Da5ZatL0SAtnA1ROyljl/d1ejPZElXBoOEJ2NeBa3X5lF54533R5vfBpfMdV79wt9A7ZISI9rGZAWwVB+xfFKUFkp4fNsRQp5ee81k8FhaBu/L33WrhCoGhRDNvIUdn4vvOkjd8fbY1Hj4OX3FxXak+yzEo6tB8suvvgTgy2ePLaF4FtO6rpfoX89sEYpMIg8LON/bRBGP/LRvywJXEdC1vSdi5ZHa3BgizewxhWw7BsQX/AByZXAc4VEBAgEV7XPzga8xf8uG24QMYsI40l78PlYTweuCUD9ZEa31GG0jAt5M5qNQfwxMieyOKEimaplNQui4tag0YBjgUo/dTUtOVTeQskZumjguvNaOsOLwd7vnvMV/N6M1GKQMz4xjnA3dY=
