language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  app: cryptic-plateau-81627
  api_key:
    secure: BANadb4IhLReSQz9nMsHCflEc0fbxBFhlHBDHBj6Agxu/JeZGhHYaxgGwZM3afjKc91otdwrAoNRX1GB3bEmm5INSxgX5P0c8hf//tJY3uyfL5cGJi5DBXFq8Z9Xrf1Lnw3qts4okiC7EYdUctxE6znuOK+AlJCfRixzUYiZKYj6HZPxzy7ZvxxPnGxbZAY1kEGW8AuDjae2WpuqqnX9rQzccLTq/5CnnIqEhMTSVRkpKlubL0TnRt+exFQgClU9JBFkOQvWm67jR6kSxsY5Lkm3zZIMJ2ExWUr7fvNgITPKZnUyt1dwRw2ChENOBsXdfhfuBsaxeNUW/rxq/9+XXEbQiJwherSg6vu7ri3ExVow+X66GoBZGh348Dw2xHJk0sLkuH3+aiSQdUqXzBpYqgijfX0ga3VTTBV1W5tWIC8BhSNSuiMBKL56YPFrEqjXs1JEOly4cTb6LnloiXxt2Bu8/NZgEGmlQGAY4H38JHK6pv6e+4H5Ksa7W2zr62tsUOHtIjS5MmSqYbmAIfXiZKguDu33yz2XtBSpZ/+Ck8sfxq5J2Wt4x/MVT/bkfP+k1ByBFpPk3e0l8b6WRGziInvIrdeLYF3BO2WwXU8vVKpAct43k4EOYaPjldF15Fj702LboLPnnBjgD3y8jbvCKuQ9fZOwrugmDM5JwgN5Z6U=
